//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Glass.Data.SMSManager {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WSManagerPortBinding", Namespace="http://webservice.comunika.com.br")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(responseGeneric))]
    public partial class WSManager : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getAuthenticationOperationCompleted;
        
        private System.Threading.SendOrPostCallback cancelScheduleMessageByBatchOperationCompleted;
        
        private System.Threading.SendOrPostCallback cancelScheduleMessageByPeriodOperationCompleted;
        
        private System.Threading.SendOrPostCallback cancelScheduleMessageByIdsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WSManager() {
            this.Url = global::Glass.Data.Properties.Settings.Default.Glass_Data_SMSManager_WSManager;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getAuthenticationCompletedEventHandler getAuthenticationCompleted;
        
        /// <remarks/>
        public event cancelScheduleMessageByBatchCompletedEventHandler cancelScheduleMessageByBatchCompleted;
        
        /// <remarks/>
        public event cancelScheduleMessageByPeriodCompletedEventHandler cancelScheduleMessageByPeriodCompleted;
        
        /// <remarks/>
        public event cancelScheduleMessageByIdsCompletedEventHandler cancelScheduleMessageByIdsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.comunika.com.br", ResponseNamespace="http://webservice.comunika.com.br", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public wsToken getAuthentication([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string login, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string pass) {
            object[] results = this.Invoke("getAuthentication", new object[] {
                        login,
                        pass});
            return ((wsToken)(results[0]));
        }
        
        /// <remarks/>
        public void getAuthenticationAsync(string login, string pass) {
            this.getAuthenticationAsync(login, pass, null);
        }
        
        /// <remarks/>
        public void getAuthenticationAsync(string login, string pass, object userState) {
            if ((this.getAuthenticationOperationCompleted == null)) {
                this.getAuthenticationOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetAuthenticationOperationCompleted);
            }
            this.InvokeAsync("getAuthentication", new object[] {
                        login,
                        pass}, this.getAuthenticationOperationCompleted, userState);
        }
        
        private void OngetAuthenticationOperationCompleted(object arg) {
            if ((this.getAuthenticationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getAuthenticationCompleted(this, new getAuthenticationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.comunika.com.br", ResponseNamespace="http://webservice.comunika.com.br", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public responseCancelMessage cancelScheduleMessageByBatch([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string token, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string batch) {
            object[] results = this.Invoke("cancelScheduleMessageByBatch", new object[] {
                        token,
                        batch});
            return ((responseCancelMessage)(results[0]));
        }
        
        /// <remarks/>
        public void cancelScheduleMessageByBatchAsync(string token, string batch) {
            this.cancelScheduleMessageByBatchAsync(token, batch, null);
        }
        
        /// <remarks/>
        public void cancelScheduleMessageByBatchAsync(string token, string batch, object userState) {
            if ((this.cancelScheduleMessageByBatchOperationCompleted == null)) {
                this.cancelScheduleMessageByBatchOperationCompleted = new System.Threading.SendOrPostCallback(this.OncancelScheduleMessageByBatchOperationCompleted);
            }
            this.InvokeAsync("cancelScheduleMessageByBatch", new object[] {
                        token,
                        batch}, this.cancelScheduleMessageByBatchOperationCompleted, userState);
        }
        
        private void OncancelScheduleMessageByBatchOperationCompleted(object arg) {
            if ((this.cancelScheduleMessageByBatchCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cancelScheduleMessageByBatchCompleted(this, new cancelScheduleMessageByBatchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.comunika.com.br", ResponseNamespace="http://webservice.comunika.com.br", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public responseCancelMessage cancelScheduleMessageByPeriod([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string token, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string begin, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string end) {
            object[] results = this.Invoke("cancelScheduleMessageByPeriod", new object[] {
                        token,
                        begin,
                        end});
            return ((responseCancelMessage)(results[0]));
        }
        
        /// <remarks/>
        public void cancelScheduleMessageByPeriodAsync(string token, string begin, string end) {
            this.cancelScheduleMessageByPeriodAsync(token, begin, end, null);
        }
        
        /// <remarks/>
        public void cancelScheduleMessageByPeriodAsync(string token, string begin, string end, object userState) {
            if ((this.cancelScheduleMessageByPeriodOperationCompleted == null)) {
                this.cancelScheduleMessageByPeriodOperationCompleted = new System.Threading.SendOrPostCallback(this.OncancelScheduleMessageByPeriodOperationCompleted);
            }
            this.InvokeAsync("cancelScheduleMessageByPeriod", new object[] {
                        token,
                        begin,
                        end}, this.cancelScheduleMessageByPeriodOperationCompleted, userState);
        }
        
        private void OncancelScheduleMessageByPeriodOperationCompleted(object arg) {
            if ((this.cancelScheduleMessageByPeriodCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cancelScheduleMessageByPeriodCompleted(this, new cancelScheduleMessageByPeriodCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.comunika.com.br", ResponseNamespace="http://webservice.comunika.com.br", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public responseCancelMessage cancelScheduleMessageByIds([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string token, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string ids) {
            object[] results = this.Invoke("cancelScheduleMessageByIds", new object[] {
                        token,
                        ids});
            return ((responseCancelMessage)(results[0]));
        }
        
        /// <remarks/>
        public void cancelScheduleMessageByIdsAsync(string token, string ids) {
            this.cancelScheduleMessageByIdsAsync(token, ids, null);
        }
        
        /// <remarks/>
        public void cancelScheduleMessageByIdsAsync(string token, string ids, object userState) {
            if ((this.cancelScheduleMessageByIdsOperationCompleted == null)) {
                this.cancelScheduleMessageByIdsOperationCompleted = new System.Threading.SendOrPostCallback(this.OncancelScheduleMessageByIdsOperationCompleted);
            }
            this.InvokeAsync("cancelScheduleMessageByIds", new object[] {
                        token,
                        ids}, this.cancelScheduleMessageByIdsOperationCompleted, userState);
        }
        
        private void OncancelScheduleMessageByIdsOperationCompleted(object arg) {
            if ((this.cancelScheduleMessageByIdsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cancelScheduleMessageByIdsCompleted(this, new cancelScheduleMessageByIdsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.comunika.com.br")]
    public partial class wsToken : responseGeneric {
        
        private System.DateTime lastUpdateField;
        
        private bool lastUpdateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime lastUpdate {
            get {
                return this.lastUpdateField;
            }
            set {
                this.lastUpdateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lastUpdateSpecified {
            get {
                return this.lastUpdateFieldSpecified;
            }
            set {
                this.lastUpdateFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(wsToken))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(responseCancelMessage))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.comunika.com.br")]
    public partial class responseGeneric {
        
        private int resultField;
        
        private string resultDescField;
        
        private string tokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string resultDesc {
            get {
                return this.resultDescField;
            }
            set {
                this.resultDescField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.comunika.com.br")]
    public partial class cancelReturn {
        
        private string idField;
        
        private int resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.comunika.com.br")]
    public partial class responseCancelMessage : responseGeneric {
        
        private cancelReturn[] msgsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("msgs", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public cancelReturn[] msgs {
            get {
                return this.msgsField;
            }
            set {
                this.msgsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void getAuthenticationCompletedEventHandler(object sender, getAuthenticationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getAuthenticationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getAuthenticationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public wsToken Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((wsToken)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void cancelScheduleMessageByBatchCompletedEventHandler(object sender, cancelScheduleMessageByBatchCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cancelScheduleMessageByBatchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cancelScheduleMessageByBatchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public responseCancelMessage Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((responseCancelMessage)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void cancelScheduleMessageByPeriodCompletedEventHandler(object sender, cancelScheduleMessageByPeriodCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cancelScheduleMessageByPeriodCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cancelScheduleMessageByPeriodCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public responseCancelMessage Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((responseCancelMessage)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void cancelScheduleMessageByIdsCompletedEventHandler(object sender, cancelScheduleMessageByIdsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cancelScheduleMessageByIdsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cancelScheduleMessageByIdsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public responseCancelMessage Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((responseCancelMessage)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591