//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Glass.UI.Web.Cadastros {
    
    
    public partial class CadCategoriaConta {
        
        /// <summary>
        /// grdCategoriaConta control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.GridView grdCategoriaConta;
        
        /// <summary>
        /// odsTipoCategoria control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Colosoft.WebControls.VirtualObjectDataSource odsTipoCategoria;
        
        /// <summary>
        /// odsCategoriaConta control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Colosoft.WebControls.VirtualObjectDataSource odsCategoriaConta;
    }
}
